### ISSUE TITLE
Basisdaten zu dem Projekt 

### ISSUE THREAD

**Issue by Miraculix666** [Bastian-Reul/Girlsday2024#1]
Hi, bitte einmal ein paar basisdaten zu dem Projekt hinterlegen.

- Default Login 
- verwendetes Image / installationsart
- Aufgaben / Übungen / Anleitung aus dem Kurs 

So stehen viele vor der Herausforderung dass sie zu Hause nicht wissen was sie weiter mit ihrem tollen Magic mirror machen können und wie sie ihn überhaupt weiter konfigurieren. 

(Ich finde den Weg, aber die Kids sollten ja möglichst eigenständig damit umgehen können)

Übrigens ein super tolles Projekt, vielen Dank!

**Comment by Bastian-Reul** [comment]
Hallo Miraculix,
vielen Dank, ich arbeite dran.
